---
apiVersion: v1
kind: Namespace
metadata:
  name: thatdot-openshift
  annotations:
    openshift.io/display-name: "thatDot OpenShift"
    openshift.io/description: "Quine Enterprise + supporting services for the Wells Fargo PoC"
